version: '3'

services:
  client:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: client
    image: client
    restart: unless-stopped
    ports:
      - '8080:8080'

  file-service:
    build:
      context: ./gm-test-app-ms
      dockerfile: ./Dockerfile
    container_name: file-service
    image: file-service
    restart: unless-stopped
    ports:
      - '8880:8880'
